##### Labeler #####
labelPRBasedOnFilePath:
  # "label": [ folder or subfolders ]
  ":package: components": [ packages/components/* ]
  ":package: config-helpers": [ packages/config-helpers/* ]
  ":package: core": [ packages/core/* ]
  ":package: create-freesewing-pattern": [ packages/create-freesewing-pattern/* ]
  ":package: css-theme": [ packages/css-theme/* ]
  ":package: gatsby-remark-jargon": [ packages/gatsby-remark-jargon/* ]
  ":package: i18n": [ packages/i18n/* ]
  ":package: models": [ packages/models/* ]
  ":package: mui-theme": [ packages/mui-theme/* ]
  ":package: new-design": [ packages/new-design/* ]
  ":package: pattern-info": [ packages/pattern-info/* ]
  ":package: prettier-config": [ packages/prettier-config/* ]
  ":package: rehype-jargon": [ packages/rehype-jargon/* ]
  ":package: remark-jargon": [ packages/remark-jargon/* ]
  ":package: utils": [ packages/utils/* ]
  ":electric_plug: plugin-banner": [ plugins/plugin-banner/* ]
  ":electric_plug: plugin-bartack": [ plugins/plugin-bartack/* ]
  ":electric_plug: plugin-bundle": [ plugins/plugin-bundle/* ]
  ":electric_plug: plugin-bust": [ plugins/plugin-bust/* ]
  ":electric_plug: plugin-buttons": [ plugins/plugin-buttons/* ]
  ":electric_plug: plugin-cutonfold": [ plugins/plugin-cutonfold/* ]
  ":electric_plug: plugin-dimension": [ plugins/plugin-dimension/* ]
  ":electric_plug: plugin-export-dxf": [ plugins/plugin-export-dxf/* ]
  ":electric_plug: plugin-flip": [ plugins/plugin-flip/* ]
  ":electric_plug: plugin-gore": [ plugins/plugin-gore/* ]
  ":electric_plug: plugin-grainline": [ plugins/plugin-grainline/* ]
  ":electric_plug: plugin-i18n": [ plugins/plugin-i18n/* ]
  ":electric_plug: plugin-logo": [ plugins/plugin-logo/* ]
  ":electric_plug: plugin-measurements": [ plugins/plugin-measurements/* ]
  ":electric_plug: plugin-mirror": [ plugins/plugin-mirror/* ]
  ":electric_plug: plugin-notches": [ plugins/plugin-notches/* ]
  ":electric_plug: plugin-round": [ plugins/plugin-round/* ]
  ":electric_plug: plugin-scalebox": [ plugins/plugin-scalebox/* ]
  ":electric_plug: plugin-sprinkle": [ plugins/plugin-sprinkle/* ]
  ":electric_plug: plugin-svgattr": [ plugins/plugin-svgattr/* ]
  ":electric_plug: plugin-theme": [ plugins/plugin-theme/* ]
  ":electric_plug: plugin-title": [ plugins/plugin-title/* ]
  ":electric_plug: plugin-validate": [ plugins/plugin-validate/* ]
  ":electric_plug: plugin-versionfree-svg": [ plugins/plugin-versionfree-svg/* ]
  ":book: documentation": [ markdown/* ]
  ":scroll: scripts": [ scripts/* ]
  ":computer: backend": [ sites/backend/* ]
  ":computer: dev": [ sites/dev/* ]
  ":computer: lab": [ sites/lab/* ]
  ":computer: org": [ sites/org/* ]
  ":computer: shared": [ sites/shared/* ]
  ":computer: strapi": [ sites/strapi/* ]
  ":computer: svgtopdf": [ sites/svgtopdf/* ]
  ":test_tube: tests": [ tests/* ]
  ":gear: configuration": [ "config/*", ".github/*" ]
  ":shirt: aaron": [ designs/aaron/* ]
  ":shirt: albert": [ designs/albert/* ]
  ":shirt: bee": [ designs/bee/* ]
  ":shirt: bella": [ designs/bella/* ]
  ":shirt: benjamin": [ designs/benjamin/* ]
  ":shirt: bent": [ designs/bent/* ]
  ":shirt: bob": [ designs/bob/* ]
  ":shirt: breanna": [ designs/breanna/* ]
  ":shirt: brian": [ designs/brian/* ]
  ":shirt: bruce": [ designs/bruce/* ]
  ":shirt: carlita": [ designs/carlita/* ]
  ":shirt: carlton": [ designs/carlton/* ]
  ":shirt: cathrin": [ designs/cathrin/* ]
  ":shirt: charlie": [ designs/charlie/* ]
  ":shirt: cornelius": [ designs/cornelius/* ]
  ":shirt: diana": [ designs/diana/* ]
  ":shirt: examples": [ designs/examples/* ]
  ":shirt: florence": [ designs/florence/* ]
  ":shirt: florent": [ designs/florent/* ]
  ":shirt: hi": [ designs/hi/* ]
  ":shirt: holmes": [ designs/holmes/* ]
  ":shirt: hortensia": [ designs/hortensia/* ]
  ":shirt: huey": [ designs/huey/* ]
  ":shirt: hugo": [ designs/hugo/* ]
  ":shirt: jaeger": [ designs/jaeger/* ]
  ":shirt: legend": [ designs/legend/* ]
  ":shirt: lucy": [ designs/lucy/* ]
  ":shirt: lunetius": [ designs/lunetius/* ]
  ":shirt: noble": [ designs/noble/* ]
  ":shirt: octoplushy": [ designs/octoplushy/* ]
  ":shirt: paco": [ designs/paco/* ]
  ":shirt: penelope": [ designs/penelope/* ]
  ":shirt: plugintest": [ designs/plugintest/* ]
  ":shirt: rendertest": [ designs/rendertest/* ]
  ":shirt: sandy": [ designs/sandy/* ]
  ":shirt: shin": [ designs/shin/* ]
  ":shirt: simon": [ designs/simon/* ]
  ":shirt: simone": [ designs/simone/* ]
  ":shirt: snapseries": [ designs/snapseries/* ]
  ":shirt: sven": [ designs/sven/* ]
  ":shirt: tamiko": [ designs/tamiko/* ]
  ":shirt: teagan": [ designs/teagan/* ]
  ":shirt: theo": [ designs/theo/* ]
  ":shirt: tiberius": [ designs/tiberius/* ]
  ":shirt: titan": [ designs/titan/* ]
  ":shirt: trayvon": [ designs/trayvon/* ]
  ":shirt: tutorial": [ designs/tutorial/* ]
  ":shirt: unice": [ designs/unice/* ]
  ":shirt: ursula": [ designs/ursula/* ]
  ":shirt: wahid": [ designs/wahid/* ]
  ":shirt: walburga": [ designs/walburga/* ]
  ":shirt: waralee": [ designs/waralee/* ]
  ":shirt: yuri": [ designs/yuri/* ]

labelerFlags:
  labelOnPRUpdates: true

##### Greetings #####
firstPRWelcomeComment: >
  Thanks for opening this pull request 😀
  Please take a moment to read [our contributing guidelines](https://github.com/freesewing/freesewing/blob/develop/CONTRIBUTING.md).

firstPRMergeComment: >
  Awesome work 🎉 congrats on your first merged pull request 🤓

  ![Welcome to the nerd zone](https://media.giphy.com/media/l0HlHFRbmaZtBRhXG/giphy.gif)

firstIssueWelcomeComment: >
  Thanks for opening your first issue here at FreeSewing 🥇

  One of our contributors should triage this soon so that it gets some attention.
  If it's urgent, you can [join us on Discord](https://discord.freesewing.org/)
  where we tend to hang out.

