author: 'Joost De Cock <joost@decock.org> (https://github.com/joostdecock)'
homepage: 'https://freesewing.org/'
repository: 'github:freesewing/freesewing'
bugsUrl: 'https://github.com/freesewing/freesewing/issues'
