_types:
  design:
    peer:
      '@freesewing/core': &freesewing '^{{version}}'
      '@freesewing/plugin-bundle': *freesewing
    dev:
      'mocha': &mocha '^10.0.0'
      'chai': &chai '^4.2.0'
  plugin:
    peer:
      '@freesewing/core': *freesewing
    dev:
      'mocha': *mocha
      'chai': *chai
aaron:
  peer:
    '@freesewing/brian': *freesewing
    '@freesewing/plugin-bust': *freesewing
bee:
  peer:
    '@freesewing/bella': *freesewing
bent:
  peer:
    '@freesewing/brian': *freesewing
    '@freesewing/plugin-mirror': *freesewing
    '@freesewing/plugin-bust': *freesewing
breanna:
  peer:
    '@freesewing/brian': *freesewing
brian:
  peer:
    '@freesewing/plugin-mirror': *freesewing
    '@freesewing/plugin-bust': *freesewing
carlita:
  peer:
    '@freesewing/brian': *freesewing
    '@freesewing/bent': *freesewing
    '@freesewing/carlton': *freesewing
    '@freesewing/plugin-bust': *freesewing
    '@freesewing/plugin-mirror': *freesewing
carlton:
  peer:
    '@freesewing/brian': *freesewing
    '@freesewing/bent': *freesewing
    '@freesewing/plugin-mirror': *freesewing
    '@freesewing/plugin-bust': *freesewing
charlie:
  peer:
    '@freesewing/plugin-bartack': *freesewing
    '@freesewing/plugin-mirror': *freesewing
    '@freesewing/titan': *freesewing
    '@freesewing/snapseries': *freesewing
core:
  _:
    'bezier-js': '^6.1.0'
    'bin-pack': '^1.0.2'
    'hooks': '^0.3.2'
    'lodash.get': &_get '4.4.2'
    'lodash.set': &_set '4.3.2'
    'lodash.unset': &_unset '4.5.2'
  dev:
    'eslint': '^8.23.1'
    'nyc': '^15.1.0'
diana:
  peer:
    '@freesewing/brian': *freesewing
    '@freesewing/plugin-bust': *freesewing
examples:
  peer:
    '@freesewing/plugin-mirror': *freesewing
    '@freesewing/plugin-gore': *freesewing
holmes:
  _:
    '@freesewing/plugin-gore': *freesewing
  peer:
    '@freesewing/plugin-bust': *freesewing
huey:
  peer:
    '@freesewing/brian': *freesewing
    '@freesewing/plugin-bust': *freesewing
hugo:
  peer:
    '@freesewing/brian': *freesewing
    '@freesewing/plugin-bust': *freesewing
i18n:
  dev:
    'js-yaml': '^4.1.0'
  peer:
    '@freesewing/pattern-info': *freesewing
jaeger:
  peer:
    '@freesewing/brian': *freesewing
    '@freesewing/bent': *freesewing
    '@freesewing/plugin-bust': *freesewing
    '@freesewing/plugin-mirror': *freesewing
lily:
  peer:
    '@freesewing/titan': *freesewing
new-design:
  _:
    'axios': '^1.1.2'
    'chalk': '^5.0.1'
    'execa': '^6.1.0'
    'mustache': '^4.2.0'
    'ora': '^6.1.0'
    'prompts': '^2.4.2'
    'recursive-readdir': '^2.2.2'
noble:
  peer:
    '@freesewing/bella': *freesewing
legend:
  peer:
    '@freesewing/plugin-buttons': *freesewing
paco:
  peer:
    '@freesewing/titan': *freesewing
    '@freesewing/snapseries': *freesewing
plugin-bundle:
  dev:
    '@freesewing/plugin-banner': *freesewing
    '@freesewing/plugin-buttons': *freesewing
    '@freesewing/plugin-cutonfold': *freesewing
    '@freesewing/plugin-dimension': *freesewing
    '@freesewing/plugin-grainline': *freesewing
    '@freesewing/plugin-logo': *freesewing
    '@freesewing/plugin-mirror': *freesewing
    '@freesewing/plugin-title': *freesewing
    '@freesewing/plugin-scalebox': *freesewing
    '@freesewing/plugin-round': *freesewing
    '@freesewing/plugin-sprinkle': *freesewing
plugintest:
  peer:
    '@freesewing/plugin-banner': *freesewing
    '@freesewing/plugin-bartack': *freesewing
    '@freesewing/plugin-bust': *freesewing
    '@freesewing/plugin-buttons': *freesewing
    '@freesewing/plugin-cutonfold': *freesewing
    '@freesewing/plugin-dimension': *freesewing
    '@freesewing/plugin-flip': *freesewing
    '@freesewing/plugin-gore': *freesewing
    '@freesewing/plugin-grainline': *freesewing
    '@freesewing/plugin-i18n': *freesewing
    '@freesewing/plugin-logo': *freesewing
    '@freesewing/plugin-measurements': *freesewing
    '@freesewing/plugin-mirror': *freesewing
    '@freesewing/plugin-notches': *freesewing
    '@freesewing/plugin-round': *freesewing
    '@freesewing/plugin-scalebox': *freesewing
    '@freesewing/plugin-sprinkle': *freesewing
    '@freesewing/plugin-svgattr': *freesewing
    '@freesewing/plugin-theme': *freesewing
    '@freesewing/plugin-title': *freesewing
    '@freesewing/plugin-validate': *freesewing
rehype-jargon:
  _:
    'unist-util-visit': '^4.1.0'
    'hast-util-from-html': '^1.0.0'
rehype-highlight-lines:
  _:
    'unist-util-remove': '^3.1.0'
sandy:
  peer:
    '@freesewing/snapseries': *freesewing
shin:
  peer:
    '@freesewing/snapseries': *freesewing
simon:
  peer:
    '@freesewing/brian': *freesewing
    '@freesewing/plugin-bust': *freesewing
    '@freesewing/plugin-flip': *freesewing
simone:
  peer:
    '@freesewing/brian': *freesewing
    '@freesewing/simon': *freesewing
    '@freesewing/plugin-flip': *freesewing
    '@freesewing/plugin-bust': *freesewing
sven:
  peer:
    '@freesewing/brian': *freesewing
    '@freesewing/plugin-bust': *freesewing
tamiko:
  peer:
    '@freesewing/plugin-bust': *freesewing
teagan:
  peer:
    '@freesewing/brian': *freesewing
    '@freesewing/plugin-bust': *freesewing
titan:
  peer:
    '@freesewing/snapseries': *freesewing
trayvon:
  peer:
    '@freesewing/snapseries': *freesewing
wahid:
  peer:
    '@freesewing/brian': *freesewing
    '@freesewing/plugin-bust': *freesewing
yuri:
  peer:
    '@freesewing/brian': *freesewing
    '@freesewing/plugin-bust': *freesewing

# Sites go here

backend:
  _:
    '@aws-sdk/client-sesv2': '^3.200.0'
    '@prisma/client': '4.7.1'
    'bcryptjs': '^2.4.3'
    'crypto': '^1.0.1'
    'express': '4.18.2'
    'mustache': '^4.2.0'
    'otplib': '^12.0.1'
    'passport': '^0.6.0'
    'passport-http': '^0.3.0'
    'passport-jwt': '^4.0.0'
    'pino': '^8.7.0'
    'qrcode': '^1.5.1'
  dev:
    'chai': *chai
    'chai-http': '^4.3.0'
    'mocha': *mocha
    'mocha-steps': '^1.3.0'
    'prisma': '4.7.1'

dev:
  _:
    '@mdx-js/loader': &mdx '2.2.1'
    '@mdx-js/mdx': *mdx
    '@mdx-js/react': *mdx
    '@mdx-js/runtime': &mdxRuntime '2.0.0-next.9'
    '@next/bundle-analyzer': &next '13.0.7'
    '@tailwindcss/typography': '0.5.8'
    'algoliasearch': '^4.11.0'
    'daisyui': &daisyui '2.45.0'
    'lodash.get': *_get
    'lodash.orderby': &_orderby '4.6.0'
    'lodash.set': *_set
    'next': *next
    'react': &react '18.2.0'
    'react-copy-to-clipboard': &reactCopyToClipboard '5.1.0'
    'react-dom': *react
    'react-hotkeys-hook': &reactHotkeysHook '4.0.6'
    'react-instantsearch-dom': &reactInstantsearchDom '6.38.1'
    'react-markdown': &reactMarkdown '8.0.4'
    'react-swipeable': &reactSwipeable '7.0.0'
    'react-timeago': &reactTimeago '7.1.0'
    'rehype-autolink-headings': &rehypeAutolinkHeadings '6.1.1'
    'rehype-highlight': &rehypeHighlight '6.0.0'
    'rehype-sanitize': &rehypeSanitize '5.0.1'
    'rehype-slug': &rehypeSlug '5.1.0'
    'rehype-stringify': &rehypeStringify '9.0.3'
    'remark-copy-linked-files': &remarkCopyLinkedFiles 'https://github.com/joostdecock/remark-copy-linked-files'
    'remark-gfm': &remarkGfm '3.0.1'
  dev: &nextSiteDevDependencies
    'autoprefixer': '10.4.13'
    'eslint-config-next': *next
    'js-yaml': &jsYaml '4.1.0'
    'postcss': &postcss '8.4.20'
    'remark-extract-frontmatter': '3.2.0'
    'tailwindcss': &tailwindcss '3.2.4'
    'yaml-loader': '0.8.0'

email:
  _:
    '@maizzle/framework': '4.3.1'
    'tailwindcss-box-shadow': '^1.0.0'
    'tailwindcss-email-variants': '^1.0.0'
    'tailwindcss-mso': '^1.2.0'

lab:
  _:
    '@headlessui/react': &headlessUiReact '^1.6.6'
    '@mdx-js/loader': *mdx
    '@mdx-js/mdx': *mdx
    '@mdx-js/react': *mdx
    '@mdx-js/runtime': *mdxRuntime
    '@tailwindcss/typography': &tailwindTypography '^0.5.0'
    'algoliasearch': &algoliasearch '4.14.2'
    'd3-dispatch': '3.0.1'
    'd3-drag': '3.0.0'
    'd3-selection': '3.0.0'
    'daisyui': *daisyui
    'i18next': &i18next '22.4.5'
    'lodash.get': *_get
    'lodash.orderby': *_orderby
    'lodash.set': *_set
    'next': *next
    'next-i18next': &nextI18next '13.0.2'
    'react': *react
    'react-copy-to-clipboard': *reactCopyToClipboard
    'react-hotkeys-hook': *reactHotkeysHook
    'react-i18next': &reactI18next '12.1.1'
    'react-instantsearch-dom': *reactInstantsearchDom
    'react-markdown': *reactMarkdown
    'react-swipeable': *reactSwipeable
    'react-timeago': *reactTimeago
    'rehype-autolink-headings': *rehypeAutolinkHeadings
    'rehype-highlight': *rehypeHighlight
    'rehype-sanitize': *rehypeSanitize
    'rehype-slug': *rehypeSlug
    'rehype-stringify': *rehypeStringify
    'remark-copy-linked-files': *remarkCopyLinkedFiles
    'remark-gfm': *remarkGfm
  dev: *nextSiteDevDependencies

org:
  _:
    '@mdx-js/loader': *mdx
    '@mdx-js/mdx': *mdx
    '@mdx-js/react': *mdx
    '@mdx-js/runtime': *mdxRuntime
    '@tailwindcss/typography': *tailwindTypography
    'algoliasearch': *algoliasearch
    'daisyui': *daisyui
    'lodash.get': *_get
    'lodash.orderby': *_orderby
    'lodash.set': *_set
    'next': *next
    'react-hotkeys-hook': *reactHotkeysHook
    'react-instantsearch-dom': *reactInstantsearchDom
    'react-markdown': *reactMarkdown
    'react-swipeable': *reactSwipeable
    'react-timeago': *reactTimeago
    'rehype-autolink-headings': *rehypeAutolinkHeadings
    'rehype-highlight': *rehypeHighlight
    'rehype-sanitize': *rehypeSanitize
    'rehype-slug': *rehypeSlug
    'rehype-stringify': *rehypeStringify
    'remark-copy-linked-files': *remarkCopyLinkedFiles
    'remark-gfm': *remarkGfm
  dev: *nextSiteDevDependencies

sanity:
  _:
    '@sanity/base': '2.35.0'
    '@sanity/core': '2.35.0'
    '@sanity/default-layout': '2.35.0'
    '@sanity/default-login': '2.35.0'
    '@sanity/desk-tool': '2.35.0'
    '@sanity/eslint-config-studio': '2.0.0'
    '@sanity/vision': '2.35.0'
    'eslint': '8.6.0'
    'prop-types': '15.7'
    'react': *react
    'react-dom': *react
    'sanity-plugin-markdown': '3.0.1'
    'styled-components': '5.2.0'
  dev:
    '@sanity/cli': '2.35.0'

shared:
  _:
    '@headlessui/react': *headlessUiReact
    '@resvg/resvg-js': '^2.1.0'
    '@tailwindcss/typography': *tailwindTypography
    'Buffer': '^0.0.0'
    'd3-dispatch': '^3.0.1'
    'd3-drag': '^3.0.0'
    'd3-selection': '^3.0.0'
    'daisyui': *daisyui
    'feed': '^4.2.2'
    'file-saver': '^2.0.5'
    'front-matter': '^4.0.2'
    'highlight.js': '^11.4.0'
    'lodash.clonedeep': '^4.5.0'
    'lodash.orderby': *_orderby
    'lodash.unset': *_unset
    'mdast-util-toc': '6.1.0'
    'pdfkit': '0.13.0'
    'postcss-for': '2.1.1'
    'react': *react
    'react-dom': *react
    'react-markdown': *reactMarkdown
    'react-sizeme': '^3.0.2'
    'react-timeago': *reactTimeago
    'react-zoom-pan-pinch': '^2.1.3'
    'rehype-autolink-headings': *rehypeAutolinkHeadings
    'rehype-highlight': *rehypeHighlight
    'remark-smartypants': '^2.0.0'
    'sharp': '^0.31.1'
    'svg-to-pdfkit': '^0.1.8'
    'to-vfile': '^7.2.2'
    'unist-util-visit': '^4.1.0'
    'web-worker': '^1.2.0'
