_:
  build: 'node build.mjs'
  clean: 'rimraf dist'
  mbuild: 'NO_MINIFY=1 node build.mjs'
  symlink: 'mkdir -p ./node_modules/@freesewing && cd ./node_modules/@freesewing && ln -s -f ../../../* . && cd -'
  test: &notests 'echo "{{name}}: No tests configured. Perhaps you''d like to do this?" && exit 0'
  vbuild: 'VERBOSE=1 node build.mjs'
  lab: "cd ../../sites/lab && yarn start"
  tips: "node ../../scripts/help.mjs"
_types:
  design:
    prettier: "npx prettier --write 'src/*.mjs' 'tests/*.mjs'"
    test: &test 'npx mocha tests/*.test.mjs'
    testci: &testci "npx mocha tests/*.test.mjs --reporter ../../tests/reporters/terse.js"
  plugin:
    prettier: "npx prettier --write 'src/*.mjs' 'tests/*.mjs'"
    test: *test
    testci: *testci
core:
  report: 'nyc report --reporter=html'
  test: 'nyc -x node_modules -x tests -x bin-pack npx mocha tests/*.test.mjs'
  testci: "nyc --silent npx mocha tests/*.test.mjs --reporter ../../tests/reporters/terse.js && nyc report --reporter=json"
  testonly: 'npx mocha tests/*.test.mjs'
i18n:
  prebuild: 'node scripts/prebuilder.mjs'
  test: *test
  testci: *testci
models:
  test: "npx mocha tests/*.test.mjs"
new-design:
  build: "SITE=new-design/shared node ../../sites/shared/prebuild/i18n-only.mjs && cp ../../scripts/banner.mjs ./lib && node build.mjs"
  mbuild: '!'
  test: '!'
  testci: '!'
  vbuild: '!'
