_:
  build: 'node build.mjs'
  clean: 'rimraf dist'
  mbuild: 'NO_MINIFY=1 node build.mjs'
  symlink: 'mkdir -p ./node_modules/@freesewing && cd ./node_modules/@freesewing && ln -s -f ../../../* . && cd -'
  test: 'echo "{{name}}: No tests configured. Perhaps you could write some?" && exit 0'
  vbuild: 'VERBOSE=1 node build.mjs'
  lab: 'cd ../../sites/lab && yarn start'
  tips: 'node ../../scripts/help.mjs'
  lint: "npx eslint 'src/**' 'tests/*.mjs'"
_types:
  design:
    prettier: "npx prettier --write 'src/*.mjs' 'tests/*.mjs'"
    test: &test 'npx mocha tests/*.test.mjs'
    testci: &testci 'npx mocha tests/*.test.mjs --reporter ../../tests/reporters/terse.js'
  plugin:
    prettier: "npx prettier --write 'src/*.mjs' 'tests/*.mjs'"
    test: *test
    testci: *testci
core:
  report: 'c8 report'
  test: 'c8 mocha tests/*.test.mjs'
  testci: 'mocha tests/*.test.mjs'
  prettier: "npx prettier --write 'src/*.mjs' 'tests/*.mjs'"
  lint: "npx eslint 'src/*.mjs' 'tests/*.mjs'"
  jsdoc: 'jsdoc -c jsdoc.json -r src'
i18n:
  prebuild: 'node scripts/prebuilder.mjs'
models:
  test: 'npx mocha tests/*.test.mjs'
new-design:
  i18n-only: 'node ../../sites/shared/prebuild/i18n-only.mjs'
  build: '!'
  wbuild: '!'
  lint: "npx eslint 'lib/*.mjs'"
  mbuild: '!'
  test: '!'
  testci: '!'
  vbuild: '!'
rehype-highlight-lines:
  build: '!'
  mbuild: '!'
  vbuild: '!'
rehype-jargon:
  lint: "npx eslint 'src/*.mjs'"
snapseries:
  lint: "npx eslint 'src/*.mjs'"
backend:
  lint: '!'
