_:
  build: 'node build.js'
  clean: 'rimraf dist'
  mbuild: 'NO_MINIFY=1 node build.js'
  symlink: 'mkdir -p ./node_modules/@freesewing && cd ./node_modules/@freesewing && ln -s -f ../../../* . && cd -'
  test: &notests 'echo "{{name}}: No tests configured. Perhaps you''d like to do this?" && exit 0'
  vbuild: 'VERBOSE=1 node build.js'
  lab: "cd ../../sites/lab && yarn start"
  tips: "node ../../scripts/help.mjs"
_types:
  design:
    prettier: "npx prettier --write 'src/*.js' 'config/*.js'"
    test: &test 'BABEL_ENV=production npx mocha tests/*.test.mjs --require @babel/register'
    testci: &testci "BABEL_ENV=production npx mocha tests/*.test.mjs --require @babel/register --reporter ../../tests/reporters/terse.js"
  plugin:
    prettier: "npx prettier --write 'src/*.js' 'tests/*.mjs'"
    test: *test
    testci: *testci
create-freesewing-pattern:
  build: '!'
  cibuild_step1: '!'
  clean: '!'
  mbuild: '!'
  test: '!'
  testci: '!'
  vbuild: '!'
css-theme:
  build: 'npx node-sass --output-style compressed src/theme.scss dist/theme.css'
  watch: 'npx node-sass --watch --output-style compressed src/theme.scss dist/theme.css'
components:
  clean: 'rimraf Blockquote && rimraf Draft && rimraf DraftConfigurator && rimraf Emblem && rimraf Example && rimraf Footer && rimraf Icon && rimraf Legend && rimraf LineDrawing && rimraf Logo && rimraf Navbar && rimraf Ogol && rimraf Robot && rimraf SampleConfigurator && rimraf Spinner && rimraf withGist && rimraf withLanguage && rimraf withStorage && rimraf Workbench'
  storybook: 'start-storybook -p 6663'
  test: *notests
core:
  coverage: 'BABEL_ENV=production nyc npm test && nyc report --reporter=text-lcov > coverage.lcov && ./node_modules/.bin/codecov'
  report: 'BABEL_ENV=production nyc report --reporter=html'
  test: 'BABEL_ENV=production nyc -x node_modules -x tests/fixtures -x bin-pack npx mocha tests/*.test.js'
  testci: "BABEL_ENV=production npx mocha tests/*.test.js --require @babel/register --reporter ../../tests/reporters/terse.js"
  testonly: 'BABEL_ENV=production npx mocha tests/*.test.js'
i18n:
  # react-scripts doesn't handle .mjs files correctly
  prebuild: 'node src/prebuild.mjs'
  test: *test
  testci: *testci
new-design:
  prebuild: "SITE=new-design/shared node ../../sites/shared/prebuild/i18n-only.mjs"
  mbuild: '!'
  test: '!'
  testci: '!'
  vbuild: '!'
  cibuild_step6: "yarn build"
pattern-info:
  cibuild_step1: '!'
  build: 'node src/prebuild.js && node build.js'
  prebuild: 'node src/prebuild.js'
utils:
  clean: "rimraf backend && rimraf camelCase && rimraf capitalize && rimraf cloneObject && rimraf convertSize && rimraf defaultGist && rimraf defaultSa && rimraf formatImperial && rimraf formatMm && rimraf isDegMeasurement && rimraf measurementAsMm && rimraf measurementDiffers && rimraf neckstimate && rimraf optionDefault && rimraf optionType && rimraf roundMm && rimraf roundMmDown && rimraf roundMmUp && rimraf sliderStep && rimraf smallestImperialStep && rimraf storage && rimraf tiler && rimraf validateEmail && rimraf validateTld"
